
import type { Timestamp } from "firebase/firestore";

// This is the shape of the Web Push API's PushSubscription object
export type PushSubscription = {
  endpoint: string;
  expirationTime?: number | null;
  keys: {
    p256dh: string;
    auth: string;
  };
};

export type User = {
  id: string; // This is the document ID from Firestore
  uid: string; // This is the Firebase Auth UID
  name: string;
  email: string;
  avatar: string;
  online?: boolean;
  lastSeen?: Timestamp;
  privacySettings?: {
    showOnlineStatus?: boolean;
    showLastSeen?: boolean;
  };
  blockedUsers?: string[];
  coins: number;
  systemMessagesQueue?: string[]; // Array of messages to be delivered by the system bot
  pushSubscription?: PushSubscription | null; // For web push notifications
};

export type ReplyTo = {
  messageId: string;
  messageText: string;
  senderId: string;
  senderName: string;
  type?: Message['type'];
  fileName?: string;
}

export type Message = {
  id: string;
  text: string;
  senderId: string; // Firebase Auth UID
  timestamp: Timestamp | Date;
  type?: 'text' | 'image' | 'file' | 'audio'; // To distinguish message types
  fileURL?: string; // URL for the file/image/audio
  fileName?: string; // Name of the file
  status?: 'sent' | 'read';
  deletedFor?: string[]; // Array of user UIDs for whom the message is deleted
  isDeleted?: boolean; // True if deleted for everyone
  replyTo?: ReplyTo;
  isAutoReply?: boolean; // True if the message was generated by AI
};

export type Contact = User & {
  lastMessage?: string;
  lastMessageTimestamp?: Timestamp;
  unreadMessages?: number;
};

export type Chat = {
  id: string;
  users: string[]; // array of user UIDs
  contact: Contact; // The other user in the chat
  messages: Message[];
  createdAt: Timestamp;
  encrypted?: boolean;
  chatPassword?: string;
};

export type WithdrawalRequest = {
    id?: string;
    userId: string;
    email: string;
    amount: number;
    status: 'pending' | 'approved' | 'rejected';
    createdAt: Timestamp;
    updatedAt?: Timestamp;
    // --- Vodafone Cash Specific ---
    type: 'vodafone-cash' | 'fakka-card' | 'mobile-topup';
    vodafoneNumber?: string;
    // --- Fakka Card Specific ---
    operator?: 'Vodafone' | 'Etisalat' | 'Orange';
};
